package br.edu.ifrn.Gui;

import br.edu.ifrn.bancodedados.AlunoDao;
import br.edu.ifrn.bancodedados.Operacoes;
import java.awt.PopupMenu;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 20171214010007
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        btSorteio = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        pnLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        cbTurma = new javax.swing.JComboBox<>();
        Menu = new javax.swing.JMenuBar();
        meOpcoes = new javax.swing.JMenu();
        imSortear = new javax.swing.JMenuItem();
        imCadastrar = new javax.swing.JMenuItem();
        imRemover = new javax.swing.JMenuItem();
        imEditar = new javax.swing.JMenuItem();
        imListar = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        jFrame1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial\n");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 410));
        setResizable(false);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        btSorteio.setBackground(new java.awt.Color(153, 255, 153));
        btSorteio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btSorteio.setText("Sortear");
        btSorteio.setToolTipText("");
        btSorteio.setBorder(null);
        btSorteio.setBorderPainted(false);

        btSair.setBackground(new java.awt.Color(255, 102, 102));
        btSair.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btSair.setText("Sair");
        btSair.setBorderPainted(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        pnLogo.setBackground(new java.awt.Color(204, 255, 255));
        pnLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo3.png"))); // NOI18N
        pnLogo.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        cbTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        meOpcoes.setText("Opções");

        imSortear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        imSortear.setText("Sortear");
        meOpcoes.add(imSortear);

        imCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        imCadastrar.setBackground(new java.awt.Color(102, 102, 102));
        imCadastrar.setText("Cadastrar");
        imCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCadastrarActionPerformed(evt);
            }
        });
        meOpcoes.add(imCadastrar);

        imRemover.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        imRemover.setText("Remover");
        imRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imRemoverActionPerformed(evt);
            }
        });
        meOpcoes.add(imRemover);

        imEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        imEditar.setText("Editar");
        imEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imEditarActionPerformed(evt);
            }
        });
        meOpcoes.add(imEditar);

        imListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        imListar.setText("Listar");
        imListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imListarActionPerformed(evt);
            }
        });
        meOpcoes.add(imListar);

        Menu.add(meOpcoes);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btSorteio, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                            .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(cbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCadastrarActionPerformed

        TelaCadastro tc = new TelaCadastro(this, true);
        tc.setVisible(true);

    }//GEN-LAST:event_imCadastrarActionPerformed

    private void imEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imEditarActionPerformed

    private void imListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imListarActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void imRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imRemoverActionPerformed
        
        int id = Integer.getInteger(JOptionPane.showInputDialog(this, "Digite o id do aluno ou que deseja remover:", "Remover", 1));
        
        AlunoDao ad = new AlunoDao();
        ad.removerAluno(id);
        
    }//GEN-LAST:event_imRemoverActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSorteio;
    private javax.swing.JComboBox<String> cbTurma;
    private javax.swing.JMenuItem imCadastrar;
    private javax.swing.JMenuItem imEditar;
    private javax.swing.JMenuItem imListar;
    private javax.swing.JMenuItem imRemover;
    private javax.swing.JMenuItem imSortear;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JMenu meOpcoes;
    private javax.swing.JPanel pnLogo;
    // End of variables declaration//GEN-END:variables
}
